### ISSUE TITLE
Use filebeat and logstash to ingest commands.log

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat2-task-management#286]
Assume that  `filebeat` and `logstash` installed.
- what's the config example for filebeat to harvest the commands.log (leverage `multiline`)
- what's the config example for logstash to filter and ingest into ES  (Input/Filter/Output)

**Comment by robin2008** [comment]
There is no special config for `filebeat`,  below is the configuration to collect the commands log with `multiline` plugin.

```
filebeat.prospectors:
- type: log
  paths:
    - /var/log/xcat/commands.log*
  document_type: xcat-commands-log
  scan_frequency: 10s
  fields:
    xcat: true
    logtype: xcat-commands-log
  #ignore_older: 1h
  exclude_lines: ['^==============']
  ### Multiline options
  multiline.pattern: '^\[Date]'
  multiline.negate: true
  multiline.match: after
  multiline.flush_pattern: '^\[ElapsedTime]'
  max_lines: 10000
  timeout: 300s

output.logstash:
  hosts: ["127.0.0.1:5044"]
```
