### ISSUE TITLE
Use filebeat and logstash to ingest cluster.log

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat2-task-management#287]
1, `filebeat` monitor cluster.log and forward to logstash
2, logstash match the log message and ingest to ES
(xCAT made some changes on `rsyslog` config for its own format. Need special `grok` for it)

**Comment by robin2008** [comment]
The logstash config as below:

```
input {
 beats {
   port => 5044
  }
}
filter {
  if [fields][logtype] == "xcat-cluster-log" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{SYSLOGHOST:hostname} %{SYSLOGPROG:}: %{LOGLEVEL:severity} %{GREEDYDATA:message}" }
      overwrite => [ "message" ]
    }
  }
}
output {
  #stdout {
  #    codec => rubydebug
  #}

  if [fields][logtype] == "xcat-cluster-log" {
    elasticsearch {
      hosts => ["127.0.0.1:9200"]
      index => "logstash-xcat-cluster-%{+YYYY.MM.dd}"
    }
  }
}
```

**Comment by robin2008** [comment]
Filebeat config:

```
filebeat.prospectors:
- type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /var/log/xcat/cluster.log*
  scan_frequency: 10s
  fields:
    xcat: true
    logtype: xcat-cluster-log

output.logstash:
  hosts: ["127.0.0.1:9200"]
```
