### ISSUE TITLE
[Containerization] Run xcat container with ICP

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat2-task-management#535]
This is the first try to see if we can start xcat container successfully in ICP, and know if there any blocks for xcat.
- [x] steps to run xcat container in ICP
- [x] check if there are ports conflicts when using `host` networking

This output will be a base for future ICP integration.

**Comment by robin2008** [comment]
- Prepare the environment

Note: 
1. Here assume that you have already an ICP 3.1.0 cluster (https://10.6.7.1:8443)
2. And `kubectl` is installed on your laptop (You can use web console too)
3. You need an admin account

1, Configure client,  Follow-up the steps (https://www.ibm.com/support/knowledgecenter/SSBS6K_3.1.0/manage_cluster/cfc_cli.html) 
2, Verify if `kubectl` working, 
Note:  here our icp cluster is behind the proxy `export myproxy=<your proxy server:port>`
```
HTTPS_PROXY=http://$myproxy kubectl get namespace
NAME           STATUS    AGE
cert-manager   Active    4d
default        Active    4d
ibmcom         Active    4d
istio-system   Active    4d
kube-public    Active    4d
kube-system    Active    4d
platform       Active    4d
services       Active    4d
```
3, create the namespace `xcat` for our testing
```
HTTPS_PROXY=http://$myproxy kubectl create namespace xcat
namespace "xcat" created
```

**Comment by robin2008** [comment]
Found below error when I try to using image in my own repository `docker.io/robin2008`
```
Error from server (InternalError): Internal error occurred: admission webhook "trust.hooks.securityenforcement.admission.cloud.ibm.com" denied the request:
Deny "docker.io/robin2008/xcat-ppc64le:2.14.5", no matching repositories in the ImagePolicies
```

**Cause**: for IBM Cloud Private 3.1.1, running a docker image from any external resources has been tightly controlled.

**Action**: define the whitelist for the image policy
```
cat /tmp/ip.yaml
apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ClusterImagePolicy
metadata:
  name: my-repo-whitelist
spec:
  repositories:
    - name: docker.io/robin2008/*
HTTPS_PROXY=http://$myproxy kubectl create -f /tmp/ip.yaml
clusterimagepolicy.securityenforcement.admission.cloud.ibm.com "my-repo-whitelist" created
```

**Comment by robin2008** [comment]
Unfortunately,  ICP still cannot create the POD after the deployment created. 
```
kubectl --namespace xcat get deployment
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
xcatmn    1         0         0            0           2m
```
- Check the details of the deployment, and fount it is failed to create the `ReplicaFailure`
```
kubectl --namespace xcat describe deployment xcatmn
Name:                   xcatmn
Namespace:              xcat
CreationTimestamp:      Tue, 18 Dec 2018 01:56:25 -0500
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision=1
Selector:               app=xcatmn
Replicas:               1 desired | 0 updated | 0 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=xcatmn
  Containers:
   xcatmn:
    Image:        docker.io/robin2008/xcat-ppc64le:2.14.5
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  Progressing      True    NewReplicaSetCreated
  Available        False   MinimumReplicasUnavailable
  ReplicaFailure   True    FailedCreate
OldReplicaSets:    <none>
NewReplicaSet:     xcatmn-769d78d79c (0/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  2m    deployment-controller  Scaled up replica set xcatmn-769d78d79c to 1
```
- check the details of the failed `NewReplicaSet`
```
kubectl --namespace xcat describe rs xcatmn-769d78d79c
Name:           xcatmn-769d78d79c
Namespace:      xcat
Selector:       app=xcatmn,pod-template-hash=3258348357
Labels:         app=xcatmn
                pod-template-hash=3258348357
Annotations:    deployment.kubernetes.io/desired-replicas=1
                deployment.kubernetes.io/max-replicas=2
                deployment.kubernetes.io/revision=1
Controlled By:  Deployment/xcatmn
Replicas:       0 current / 1 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=xcatmn
           pod-template-hash=3258348357
  Containers:
   xcatmn:
    Image:        docker.io/robin2008/xcat-ppc64le:2.14.5
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                From                   Message
  ----     ------        ----               ----                   -------
  Warning  FailedCreate  29s (x17 over 4m)  replicaset-controller  Error creating: pods "xcatmn-769d78d79c-" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
```
Okay, the default security rules does not support `host` networking and `Privileged` mode.

**Comment by robin2008** [comment]
Try to follow the doc https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.1.0/app_center/nd_helm.html to enable privileged and host networking for `xcat` namespace.

Here we just use the default Pod security policy ``, better to create a dedicate one.
1. create a ClusterRole
```
cat /tmp/xcatmn-role.yaml
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRole
 metadata:
  name: xcatmn-role
 rules:
  -
    apiGroups:
      - extensions
    resourceNames:
      - privileged
    resources:
      - podsecuritypolicies
    verbs:
      - use
HTTPS_PROXY=http://$myproxy kubectl create -f /tmp/xcatmn-role.yaml
clusterrole.rbac.authorization.k8s.io "xcatmn-role" created
```
2. create a ClusterRoleBinding, and set up cluster role binding for the service account in required namespace `xcat`.
```
cat /tmp/xcatmn-rolebinding.yaml
 apiVersion: rbac.authorization.k8s.io/v1
 kind: ClusterRoleBinding
 metadata:
  name: xcatmn-users
 roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xcatmn
 subjects:
  -
    apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "system:serviceaccounts:xcat"

HTTPS_PROXY=http://$myproxy kubectl create -f /tmp/xcatmn-rolebinding.yaml
clusterrolebinding.rbac.authorization.k8s.io "xcatmn-users" created

```
